### ISSUE TITLE
permalinks broke discus

### ISSUE THREAD

**Issue by ghost** [laozhu/hugo-nuo#27]
when i active permalinks on config.toml

[permalinks]
  post = "/:title/"

my site 
https://abdiasriver.github.io/post/web-github-linux-hugo/     
change  to    https://abdiasriver.github.io/web-github-linux-hugo/

but appears with the two direccions  (duplicated content)   and the comments with discus has broken and not show on my blog, what can i do for fix this,, thanks for these awesome theme

**Comment by laozhu** [comment]
I can not totally get your meaning, the default comment system `hugo-nuo` using is [changyan](https://changyan.kuaizhan.com/) which is popular in China only, If you want to switch to Disqus, you should turn [changyan](https://changyan.kuaizhan.com/) false then set Disqus username in config.toml.

```toml
# Disqus Username
disqusShortname = "your_disqus_username_here"

[params]
  # Changyan Comments (China Only)
  changyan = false
  changyanId = "changyan_id_here"
  changyanConf = "changyan_conf_secret_here"
```

The Disqus comment system gets comments list with the unique permalink, if you change the permalinks pattern, it will be broken.

And the duplicated content problem can be solved by removing public directory before Hugo static site generates.

```bash
rm -rf public | hugo
```

Hoping the above information is helpful for you :)
