### ISSUE TITLE
Socials not show 

### ISSUE THREAD

**Issue by ghost** [laozhu/hugo-nuo#30]
Hi on he first point, thank you for this awesome theme, is minimal and very fast with hugo.

my problem is the next

- i dont see the social icons on my blog , i has added my  username but dont appear.

i got to your site demo and the same problem , any solution?

**Comment by laozhu** [comment]
I use media query for socials display [code link](https://github.com/laozhu/hugo-nuo/blob/91983c86fdcfdf44aa26eebd010f8ae54b110a2c/src/styles/partials/header.scss#L130)

```css
@media screen and (max-height: 768px) and (min-width: 800px)
.social-menu {
    display: none;
}
```

And I can see socials in [your blog](https://usuariodel.club/) now, maybe your screen height is < 768px?
