### ISSUE TITLE
social links and footer not showing

### ISSUE THREAD

**Issue by laher** [laozhu/hugo-nuo#44]
In my site I'm not seeing any social links or the main footer unless I make my window very narrow to force 'mobile' layout (or zoom in a lot). I tried with Chrome and Firefox.

See www.laher.net.nz (source at https://github.com/laher/laher.github.com )

Please could you either tweak the css or provide a way to include some custom css. 
Ta.

My User Agent
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

My Screen Resolution
1280×720

**Comment by laher** [comment]
Here's an article about custom css files in a hugo theme: https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/4

**Comment by laozhu** [comment]
Because I hide social links when the viewport [width > 800px and height < 768px](https://github.com/laozhu/hugo-nuo/blob/master/src/styles/partials/header.scss#L130).

```scss
$tablet: 800px; // Response to mobile layout
$min-height: 768px; // Hide social-menu

.social-menu {
  @media screen and (min-width: $tablet) and (max-height: $min-height) {
    display: none;
  }
}
```

Your Screen Resolution: 1280×720, So the social links is hidden :)
You can override this css rules in your template header `<style>` or you can build from [source](https://github.com/laozhu/hugo-nuo/tree/master/src/styles), before build styles from source, you need install [sass](http://sass-lang.com/).
