### ISSUE TITLE
手机端 hugo themes 收缩的按钮

### ISSUE THREAD

**Issue by TonyFly3000** [laozhu/hugo-nuo#81]
Hi laozhu,
感谢提供hugo-nuo模板。
请教一下。我怎么样可以将左边的内容在iphone 版里 做成一个收缩的按钮。

像
https://github.com/gcushen/hugo-academic 
或
https://laozhu.me/
一样

谢谢

**Comment by laozhu** [comment]
用 Media Query 写左边的内容在移动端的样式，然后对于一些从桌面 => 移动变化的 CSS 属性值加上 CSS transition 的过渡动画。

**Comment by TonyFly3000** [comment]
我应该 加 Media Query 在 hugo-nuo/src/styles/partials/header.css 吗？
我想如果是 小于 400p 就完全不展示左边。只展示右边的内容的话我应该怎么写？


@media (max-width: 400px) {

}

谢谢

**Comment by laozhu** [comment]
```css
@media screen and (max-width: 400px) {
  .site-header {
    display: none;
  }
}
```

这样就行了，不过 display 是不会加动画的。
